name             'eas-jenkins'
maintainer       'opscale'
maintainer_email 'cookbooks@opscale.com'
license          'Apache 2.0'
description      'Installs/Configures eas-jenkins'
long_description 'Installs/Configures eas-jenkins'
version          '0.1.0'

depends 'jenkins'
depends 'git'
